blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://faf.one
    about: Read the full documentation
  - name: Website
    url: https://faf.one
    about: Visit the FAF project website
